name: Pages
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@master
    - uses: actions/checkout@master

    - name: Dependencies
      run: |
        git fetch origin gh-pages  # checkout depth=1 doesn't include this branch
        python -m pip install --upgrade pip
        pip install furo  # furo theme for sphinx
        pip install numpy
        pip install git+https://github.com/psychopy/psychopy-lib --prefer-binary

    - name: Install self
      run: |
        pip install -e .

    - name: Build and Commit
      uses: sphinx-notes/pages@v2

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages